import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import authRoutes from './routes/auth.routes.js';
import concessionsRoutes from './routes/concessions.routes.js';
import employeesRoutes from './routes/employees.routes.js';
import empDocsRoutes from './routes/empdocs.routes.js';
import userRoutes from './routes/userRoutes.js';

const app = express();
app.use(cors());
app.use(morgan('dev'));
app.use(express.json());
app.get('/api/health', (req, res) => res.json({ ok: true }));
app.use('/api/auth', authRoutes);
app.use('/api/concessions', concessionsRoutes);
app.use('/api/employees', employeesRoutes);
app.use('/api/employees', empDocsRoutes); 
app.use('/api/auth/users', userRoutes);
export default app;
